# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsm < Formula
  desc "CLI tool to simplify AWS profiles, credentials, and sessions"
  homepage "https://github.com/AleG03/awsm"
  version "1.5.0"
  license "BUSL-1.1"

  on_macos do
    on_intel do
      url "https://github.com/AleG03/awsm/releases/download/v1.5.0/awsm_1.5.0_darwin_amd64.tar.gz"
      sha256 "ab3304926a9efdb465f6aa2e9c2a4a81fe47f7d0f088f3fb5e21b126c58a10af"

      def install
        bin.install "awsm"
        bash_completion.install "completions/awsm.bash" => "awsm"
        zsh_completion.install "completions/_awsm" => "_awsm"
        fish_completion.install "completions/awsm.fish"
      end
    end
    on_arm do
      url "https://github.com/AleG03/awsm/releases/download/v1.5.0/awsm_1.5.0_darwin_arm64.tar.gz"
      sha256 "66e726221eb6ecd3482c32fad050e7ac7816d3ed5712892139d400603f55aee0"

      def install
        bin.install "awsm"
        bash_completion.install "completions/awsm.bash" => "awsm"
        zsh_completion.install "completions/_awsm" => "_awsm"
        fish_completion.install "completions/awsm.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AleG03/awsm/releases/download/v1.5.0/awsm_1.5.0_linux_amd64.tar.gz"
        sha256 "9c0a32805afd303b616f24783faf1858a73a45aeaffa480f7d2315605c7d2e05"

        def install
          bin.install "awsm"
          bash_completion.install "completions/awsm.bash" => "awsm"
          zsh_completion.install "completions/_awsm" => "_awsm"
          fish_completion.install "completions/awsm.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AleG03/awsm/releases/download/v1.5.0/awsm_1.5.0_linux_arm64.tar.gz"
        sha256 "3e8a95c4e91b2adc573b083e91b89ae1688fdae61dc65cbde4eb90306f1efb4b"

        def install
          bin.install "awsm"
          bash_completion.install "completions/awsm.bash" => "awsm"
          zsh_completion.install "completions/_awsm" => "_awsm"
          fish_completion.install "completions/awsm.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/awsm", "--version"
  end
end
