# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsm < Formula
  desc "CLI tool to simplify AWS profiles, credentials, and sessions"
  homepage "https://github.com/AleG03/awsm"
  version "1.3.13"
  license "BUSL-1.1"

  on_macos do
    on_intel do
      url "https://github.com/AleG03/awsm/releases/download/v1.3.13/awsm_1.3.13_darwin_amd64.tar.gz"
      sha256 "e77b9ee3b7a26e9cc91996a0ded9ba79937ba24828b764bdeac0b7da88fe4af3"

      def install
        bin.install "awsm"
        bash_completion.install "completions/awsm.bash" => "awsm"
        zsh_completion.install "completions/_awsm" => "_awsm"
        fish_completion.install "completions/awsm.fish"
      end
    end
    on_arm do
      url "https://github.com/AleG03/awsm/releases/download/v1.3.13/awsm_1.3.13_darwin_arm64.tar.gz"
      sha256 "84d6eb1f39536beaf36c39e3736d989eb4ac46a37082db9c566971bad5c8ac61"

      def install
        bin.install "awsm"
        bash_completion.install "completions/awsm.bash" => "awsm"
        zsh_completion.install "completions/_awsm" => "_awsm"
        fish_completion.install "completions/awsm.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AleG03/awsm/releases/download/v1.3.13/awsm_1.3.13_linux_amd64.tar.gz"
        sha256 "fe7508efb1b48bfdebfd7f9daf73ca7ceca071b8e11ae9686777a77d34caadb8"

        def install
          bin.install "awsm"
          bash_completion.install "completions/awsm.bash" => "awsm"
          zsh_completion.install "completions/_awsm" => "_awsm"
          fish_completion.install "completions/awsm.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AleG03/awsm/releases/download/v1.3.13/awsm_1.3.13_linux_arm64.tar.gz"
        sha256 "ee5b38011e9416c24d7c61eabae99a58ad8ff266714399d754acfa31df745b9d"

        def install
          bin.install "awsm"
          bash_completion.install "completions/awsm.bash" => "awsm"
          zsh_completion.install "completions/_awsm" => "_awsm"
          fish_completion.install "completions/awsm.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/awsm", "--version"
  end
end
