# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsm < Formula
  desc "CLI tool to simplify AWS profiles, credentials, and sessions"
  homepage "https://github.com/AleG03/awsm"
  version "1.5.3"
  license "BUSL-1.1"

  on_macos do
    on_intel do
      url "https://github.com/AleG03/awsm/releases/download/v1.5.3/awsm_1.5.3_darwin_amd64.tar.gz"
      sha256 "1abc2e83b15981502895617a6fe74497b9ee447deeb62cd7da4b0f10b19347f4"

      def install
        bin.install "awsm"
        bash_completion.install "completions/awsm.bash" => "awsm"
        zsh_completion.install "completions/_awsm" => "_awsm"
        fish_completion.install "completions/awsm.fish"
      end
    end
    on_arm do
      url "https://github.com/AleG03/awsm/releases/download/v1.5.3/awsm_1.5.3_darwin_arm64.tar.gz"
      sha256 "d911698f4e0200f50bff49bdb1632ea70d8c9337a50c51ad7c0f89ce5d9a05ad"

      def install
        bin.install "awsm"
        bash_completion.install "completions/awsm.bash" => "awsm"
        zsh_completion.install "completions/_awsm" => "_awsm"
        fish_completion.install "completions/awsm.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AleG03/awsm/releases/download/v1.5.3/awsm_1.5.3_linux_amd64.tar.gz"
        sha256 "f9eff780cba8c19ece7724989dc6d9e94e6309845527e27e66daea04ddb01a3e"

        def install
          bin.install "awsm"
          bash_completion.install "completions/awsm.bash" => "awsm"
          zsh_completion.install "completions/_awsm" => "_awsm"
          fish_completion.install "completions/awsm.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AleG03/awsm/releases/download/v1.5.3/awsm_1.5.3_linux_arm64.tar.gz"
        sha256 "2c196b239d0f431d0830e2b265b742a809407725b1253313f27a1a14ce562efc"

        def install
          bin.install "awsm"
          bash_completion.install "completions/awsm.bash" => "awsm"
          zsh_completion.install "completions/_awsm" => "_awsm"
          fish_completion.install "completions/awsm.fish"
        end
      end
    end
  end

  test do
    system "#{bin}/awsm", "--version"
  end
end
